v1 = input('Digite alguma coisa:')
print('O tipo primitivo desse valor é:', type(v1))
print('É um numero?',v1.isnumeric())
print('É um espaço?',v1.isspace())
print('É um alfanumerico?', v1.isalnum())
print('É um alfabético?', v1.isalpha())
print('Está em maiusculas?', v1.isupper())
print('Está em minusculas?', v1.islower())
print('Está capitalizada?', v1.istitle())
